name: leet solutions test

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  
  jobs:
    build-and-test:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
  
        - name: Install Bun
          run: |
            curl -fsSL https://bun.sh/install | bash
          shell: bash
  
        - name: Set up Bun
          run: echo "::add-path::$(bun bin)" # Add Bun to the PATH
  
        - name: Install Dependencies
          run: bun install
  
        - name: Run Tests
          run: bun test
          working-directory: __test__