name: leet solutions test

on:
    push:
      branches:
        - '*'
    pull_request:
      branches:
        - main
    schedule:
        - cron: '0 6 * * *'  # Runs every day at 6:00 AM UTC
        - cron: '0 18 * * *' # Runs every day at 6:00 PM UTC
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can specify the version, like '16' or '18' as needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Compile TypeScript
      - name: Compile TypeScript
        run: npm run build  # Assumes `build` script exists in package.json

      # Step 5: Run tests
      - name: Run tests
        run: npm test  # Assumes `test` script exists in package.json
